/** @type {import('tailwindcss').Config} */

module.exports = {
    content: ["./app/**/*.{ts,tsx,jsx,js}"],
    experimental: { matchVariant: true },
    theme: {
        spacing: {
            "3xs": "var(--space-3xs)",
            "2xs": "var(--space-2xs)",
            xs: "var(--space-xs)",
            s: "var(--space-s)",
            m: "var(--space-m)",
            l: "var(--space-l)",
            xl: "var(--space-xl)",
            "2xl": "var(--space-2xl)",
            "3xl": "var(--space-3xl)",
            "4xl": "var(--space-4xl)",
            "5xl": "var(--space-5xl)",
            "6xl": "var(--space-6xl)",
            "3xs->2xs": "var(--space-3xs-2xs)",
            "2xs->xs": "var(--space-2xs-xs)",
            "xs->s": "var(--space-xs-s)",
            "s->m": "var(--space-s-m)",
            "m->l": "var(--space-m-l)",
            "l->xl": "var(--space-l-xl)",
            "xl->2xl": "var(--space-xl-2xl)",
            "2xl->3xl": "var(--space-2xl-3xl)",
            "3xl->4xl": "var(--space-3xl-4xl)",
            "4xl->5xl": "var(--space-4xl-5xl)",
            "5xl->6xl": "var(--space-5xl-6xl)",
            "3xs->xs": "var(--space-3xs-xs)",
            "2xs->s": "var(--space-2xs-s)",
            "xs->m": "var(--space-xs-m)",
            "s->l": "var(--space-s-l)",
            "m->xl": "var(--space-m-xl)",
            "l->2xl": "var(--space-l-2xl)",
            "xl->3xl": "var(--space-xl-3xl)",
            "2xl->4xl": "var(--space-2xl-4xl)",
            "3xl->5xl": "var(--space-3xl-5xl)",
            "4xl->6xl": "var(--space-4xl-6xl)",
            "3xs->s": "var(--space-3xs-s)",
            "2xs->m": "var(--space-2xs-m)",
            "xs->l": "var(--space-xs-l)",
            "s->xl": "var(--space-s-xl)",
            "m->2xl": "var(--space-m-2xl)",
            "l->3xl": "var(--space-l-3xl)",
            "xl->4xl": "var(--space-xl-4xl)",
            "2xl->5xl": "var(--space-2xl-5xl)",
            "3xl->6xl": "var(--space-3xl-6xl)",
            "3xs->m": "var(--space-3xs-m)",
            "2xs->l": "var(--space-2xs-l)",
            "xs->xl": "var(--space-xs-xl)",
            "s->2xl": "var(--space-s-2xl)",
            "m->3xl": "var(--space-m-3xl)",
            "l->4xl": "var(--space-l-4xl)",
            "xl->5xl": "var(--space-xl-5xl)",
            "2xl->6xl": "var(--space-2xl-6xl)",
            "3xs->l": "var(--space-3xs-l)",
            "2xs->xl": "var(--space-2xs-xl)",
            "xs->2xl": "var(--space-xs-2xl)",
            "s->3xl": "var(--space-s-3xl)",
            "m->4xl": "var(--space-m-4xl)",
            "l->5xl": "var(--space-l-5xl)",
            "xl->6xl": "var(--space-xl-6xl)",
        },
        fontSize: {
            "000": "var(--step--2)",
            "00": "var(--step--1)",
            0: "var(--step-0)",
            1: "var(--step-1)",
            2: "var(--step-2)",
            3: "var(--step-3)",
            4: "var(--step-4)",
            5: "var(--step-5)",
            6: "var(--step-6)",
            7: "var(--step-7)",
        },
        fontFamily: {
            sans: "var(--font-sans)",
            serif: "var(--font-serif)",
            mono: "var(--font-mono)",
        },
        borderWidth: {
            DEFAULT: "var(--border-size-1)",
            1: "var(--border-size-1)",
            2: "var(--border-size-2)",
            3: "var(--border-size-3)",
            4: "var(--border-size-4)",
            5: "var(--border-size-5)",
        },
        lineHeight: {
            "00": "var(--font-lineheight-00)",
            0: "var(--font-lineheight-0)",
            1: "var(--font-lineheight-1)",
            2: "var(--font-lineheight-2)",
            3: "var(--font-lineheight-3)",
            4: "var(--font-lineheight-4)",
            5: "var(--font-lineheight-5)",
        },
        contentWidth: {
            1: "var(--content-width-1)",
            2: "var(--content-width-2)",
            3: "var(--content-width-3)",
            4: "var(--content-width-4)",
            5: "var(--content-width-5)",
        },
        headerWidth: {
            1: "var(--header-width-1)",
            2: "var(--header-width-2)",
            3: "var(--header-width-3)",
        },
    },
    corePlugins: {
        preflight: false,
    },
    plugins: [
        ({ matchVariant }) => {
            matchVariant(
                {
                    "switcher-max-child": (val) => [
                        `& > :nth-last-child(n+${val})`,
                        `& > :nth-last-child(n+${val})~*`,
                    ],
                },
                {
                    values: {
                        2: 3,
                        3: 4,
                        4: 5,
                        5: 6,
                        6: 7,
                        7: 8,
                        8: 9,
                        9: 10,
                        10: 11,
                    },
                }
            );
        },
        require("tailwindcss-logical"),
    ],
};
